# Routes builds to run on our Trusty sudo-enabled infrastructure
# See using docker in builds: https://docs.travis-ci.com/user/docker/
sudo: required
services:
  - docker

language: ruby

env:
  global:
    - IMAGE_TAG=arm64v8
    - IMAGE_NAME=ljishen/pyben-nio:${IMAGE_TAG}

script:
  # Generate the Dockerfile-${IMAGE_TAG}
  - bash update.sh

  # Configure binfmt-support on the Docker host
  # See https://github.com/multiarch/alpine
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

  # Build image
  - docker build --cache-from "${IMAGE_NAME}" -t "${IMAGE_NAME}" . -f Dockerfile-${IMAGE_TAG}

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}"
  on:
    branch: master
