#!/usr/bin/env bash

set -eu

if [ "$#" -lt 2 ] || ([ "$1" != "--client" ] && [ "$1" != "--server" ]); then
    cat <<-ENDOFMESSAGE
Usage: ./run [--client|server] [OPTIONS]

Simple network socket benchmark.

optional arguments:
  -h, --help            show this help message and exit
  --client              Run in the client mode
  --server              Run in the server mode

For detail options for the respective mode, run
./run [-c|s] --help
ENDOFMESSAGE
    exit
fi

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ "$1" == "--server" ]; then
    "$script_dir"/server.py "${@:2}"
else
    "$script_dir"/client.py "${@:2}"
fi
